AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDLambda1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos-cf
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./index-photos-cf
      Description: 'Lambda function indexing photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::233542734977:role/service-role/codebuild-lambdaBuildProject-service-role'
      Environment:
        Variables:
          REGION: us-east-1